// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sBU3HnmlmSG3Tm8Ialv0Of5yBuBWRpM',
    appId: '1:646716831945:web:4562a22b9772fe063ef518',
    messagingSenderId: '646716831945',
    projectId: 'wastech-mobile',
    authDomain: 'wastech-mobile.firebaseapp.com',
    storageBucket: 'wastech-mobile.firebasestorage.app',
    measurementId: 'G-TBHN0T9C9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdv6GJ2_a2B5LVaWAsLDZCiuR5YMxb8sQ',
    appId: '1:646716831945:android:bdfe990eee67122f3ef518',
    messagingSenderId: '646716831945',
    projectId: 'wastech-mobile',
    storageBucket: 'wastech-mobile.firebasestorage.app',
  );
}
